"""
Extract all 88 removed questions by temporarily bypassing the manual filter.
"""
import sys, os, re, json
sys.path.insert(0, os.path.dirname(__file__))

# Before importing, monkey-patch: temporarily empty the removal set
# We do this by modifying the source in memory before importing
import importlib

# Step 1: Read the module source
src_path = os.path.join(os.path.dirname(__file__), "data", "questions_enhanced.py")
with open(src_path, "r", encoding="utf-8") as f:
    source = f.read()

# Step 2: Replace the filter line to capture the full pool  
# The filter is: QUESTIONS_POOL_ENHANCED[:] = [q for q in QUESTIONS_POOL_ENHANCED if q["question_id"] not in _MANUAL_REMOVE_IDS]
# We'll compile and exec a modified version

# Find the filter and comment it out
modified = source.replace(
    'QUESTIONS_POOL_ENHANCED[:] = [\n    q for q in QUESTIONS_POOL_ENHANCED\n    if q["question_id"] not in _MANUAL_REMOVE_IDS\n]',
    '# FILTER BYPASSED FOR EXTRACTION\npass'
)

# Create a temp module
import types
temp_module = types.ModuleType("temp_qe")
temp_module.__file__ = src_path

# We need the data package to be importable
# Actually, simpler approach: just import normally and get expansion questions
# from the builder functions, plus static questions from the filtered pool

# Let's try yet another approach - import normally, then call builders
from data.questions_enhanced import (
    QUESTIONS_POOL_ENHANCED, 
    _MANUAL_REMOVE_IDS,
    _dedup_expansion_questions,
    _semantic_dedup,
)

current_by_id = {q["question_id"]: q for q in QUESTIONS_POOL_ENHANCED}

# The expansion questions >= 1401 are generated by _build_*_expansion() 
# functions. But they go through _dedup and _semantic_dedup before reaching
# the pool. The ones we removed were the ones that survived dedup but
# we manually marked as rephrases.

# Let's try calling the expansion functions and dedup to get all pre-manual-filter questions
import data.questions_enhanced as qe_mod

# Collect all expansion questions
all_expansion = []
for name in dir(qe_mod):
    if name.startswith('_build_') and name.endswith('_expansion'):
        fn = getattr(qe_mod, name)
        if callable(fn):
            try:
                qs = fn()
                all_expansion.extend(qs)
            except:
                pass

print(f"Raw expansion questions: {len(all_expansion)}")

# Apply dedup pipeline (same as the module does)
# The module calls _dedup_expansion_questions() and _semantic_dedup()
# which modify a global list. Let's just find our IDs in the raw expansion.

expansion_by_id = {}
for q in all_expansion:
    qid = q["question_id"]
    if qid not in expansion_by_id:
        expansion_by_id[qid] = q

# Now find static questions (IDs < 1401) - these ARE in the source file literally
# Parse them from the source
static_removed_ids = [qid for qid in _MANUAL_REMOVE_IDS if qid < 1401]
expansion_removed_ids = [qid for qid in _MANUAL_REMOVE_IDS if qid >= 1401]

print(f"\nStatic removed: {len(static_removed_ids)} IDs")
print(f"Expansion removed: {len(expansion_removed_ids)} IDs")

# For static questions, find them by searching source for "question_id": NNN
static_found = {}
for qid in sorted(static_removed_ids):
    # Find the question dict in source - look for the question_id line and extract the block
    pattern = rf'"question_id":\s*{qid}\b'
    match = re.search(pattern, source)
    if match:
        # Find the enclosing dict - go backwards to find '{'
        pos = match.start()
        # Search backwards for the opening brace
        brace_count = 0
        start_pos = pos
        for i in range(pos, max(pos - 500, 0), -1):
            if source[i] == '}':
                brace_count += 1
            elif source[i] == '{':
                if brace_count == 0:
                    start_pos = i
                    break
                brace_count -= 1
        
        # Find the closing brace
        brace_count = 0
        end_pos = pos
        for i in range(start_pos, min(start_pos + 5000, len(source))):
            if source[i] == '{':
                brace_count += 1
            elif source[i] == '}':
                brace_count -= 1
                if brace_count == 0:
                    end_pos = i + 1
                    break
        
        block = source[start_pos:end_pos]
        
        # Extract fields
        text_m = re.search(r'"question_text":\s*"((?:[^"\\]|\\.)*)"', block)
        cat_m = re.search(r'"category":\s*"((?:[^"\\]|\\.)*)"', block)
        
        q_text = text_m.group(1) if text_m else "?"
        q_cat = cat_m.group(1) if cat_m else "?"
        
        # Extract options
        options = []
        opt_blocks = re.finditer(r'\{\s*"option_id":\s*(\d+)\s*,\s*"option_text":\s*"((?:[^"\\]|\\.)*)"', block)
        for ob in opt_blocks:
            options.append({"option_id": int(ob.group(1)), "option_text": ob.group(2)})
        
        # Extract all traits
        traits = set()
        for tm in re.finditer(r'"([A-Z][a-zA-Z]+-[A-Za-z-]+)":\s*([\d.]+)', block):
            traits.add(tm.group(1))
        
        static_found[qid] = {
            "question_id": qid,
            "category": q_cat,
            "question_text": q_text,
            "option_count": len(options),
            "options_preview": [o["option_text"][:60] for o in options[:4]],
            "traits": sorted(traits),
        }
    else:
        print(f"  Q{qid}: NOT FOUND in source")

print(f"\nStatic questions found: {len(static_found)}")

# For expansion questions, find them in the raw builder output
expansion_found = {}
for qid in sorted(expansion_removed_ids):
    q = expansion_by_id.get(qid)
    if q:
        traits = set()
        for o in q.get("options", []):
            traits.update(o.get("trait_tags", {}).keys())
        expansion_found[qid] = {
            "question_id": qid,
            "category": q["category"],
            "question_text": q["question_text"],
            "option_count": len(q.get("options", [])),
            "options_preview": [o["option_text"][:60] for o in q.get("options", [])[:4]],
            "traits": sorted(traits),
            "full_options": q.get("options", []),
        }
    else:
        print(f"  Q{qid}: NOT FOUND in expansion builders")

print(f"Expansion questions found: {len(expansion_found)}")

# Combine all found
all_removed = {}
all_removed.update(static_found)
all_removed.update(expansion_found)
print(f"\nTotal removed questions reconstructed: {len(all_removed)} / {len(_MANUAL_REMOVE_IDS)}")

# Show summary grouped by category
from collections import defaultdict
by_cat = defaultdict(list)
for qid, info in sorted(all_removed.items()):
    by_cat[info["category"]].append(info)

print(f"\n{'='*70}")
print(f"REMOVED QUESTIONS BY CATEGORY")
print(f"{'='*70}")

for cat in sorted(by_cat.keys()):
    qs = by_cat[cat]
    print(f"\n[{cat}] - {len(qs)} removed")
    for q in qs:
        print(f"  Q{q['question_id']}: {q['question_text'][:90]}")
        print(f"    Traits: {q['traits'][:6]}")

# Also show what each was a rephrase of
print(f"\n{'='*70}")
print(f"REPHRASE MAPPING (removed -> kept parent)")
print(f"{'='*70}")

# Parse the _MANUAL_REMOVE_IDS comments
remove_section = re.search(r'_MANUAL_REMOVE_IDS\s*=\s*\{([^}]+)\}', source)
if remove_section:
    for line in remove_section.group(1).split('\n'):
        line = line.strip()
        if not line or line.startswith('#'):
            continue
        id_match = re.match(r'(\d+)', line)
        if id_match:
            qid = int(id_match.group(1))
            comment = line.split('#', 1)[1].strip() if '#' in line else ''
            parent_match = re.search(r'Q(\d+)', comment)
            parent_id = int(parent_match.group(1)) if parent_match else None
            
            removed_info = all_removed.get(qid, {})
            removed_text = removed_info.get("question_text", "?")[:50]
            removed_cat = removed_info.get("category", "?")
            
            parent_q = current_by_id.get(parent_id)
            parent_text = parent_q["question_text"][:50] if parent_q else "NOT IN POOL"
            
            print(f"  Q{qid} ({removed_cat})")
            print(f"    Removed: {removed_text}")
            print(f"    Parent Q{parent_id}: {parent_text}")

# Save full data
with open("removed_full_data.json", "w", encoding="utf-8") as f:
    json.dump(all_removed, f, indent=2, ensure_ascii=False, default=str)

print(f"\nSaved {len(all_removed)} removed questions to removed_full_data.json")
